language: c++

matrix:
  include:
    - os: linux
      compiler: gcc
      sudo: required
      script: ./travis-desktop.sh
    - os: linux
      compiler: clang
      sudo: required
      script: ./travis-desktop.sh
    - os: osx
      compiler: clang
      osx_image: xcode8.3
      script: ./travis-desktop.sh
    - os: osx
      compiler: clang
      osx_image: xcode9.3
      script: ./travis-desktop.sh
    - language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - platform-tools
          - extra-google-m2repository
          - extra-android-m2repository
      install:
        - echo y | sdkmanager "ndk-bundle"
      before_script:
        - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
      script:
        - cd $TRAVIS_BUILD_DIR/code/build/android-native
        - $ANDROID_NDK_HOME/ndk-build

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get -qq update &&
      sudo apt-get -y install freeglut3-dev libsndfile1-dev libopenal-dev libxrandr-dev &&
      sudo apt-get -y install libc6:i386 libstdc++6:i386 ;
    fi

install:
  - ./setup.sh
