language: c++

matrix:
  include:
    - os: linux
      compiler: gcc
      sudo: required
      script: ./code/build/travis/desktop.sh

    - os: linux
      compiler: clang
      sudo: required
      script: ./code/build/travis/desktop.sh

    - os: osx
      compiler: clang
      osx_image: xcode8.3
      script: ./code/build/travis/desktop.sh

    - os: osx
      compiler: clang
      osx_image: xcode9.4
      script: ./code/build/travis/desktop.sh

    - os: osx
      compiler: clang
      osx_image: xcode10.3
      script: ./code/build/travis/desktop.sh

    - os: osx
      compiler: clang
      osx_image: xcode11.2
      script: ./code/build/travis/desktop.sh

    - os: osx
      compiler: clang
      osx_image: xcode8.3
      script: ./code/build/travis/ios.sh

    - os: osx
      compiler: clang
      osx_image: xcode9.4
      script: ./code/build/travis/ios.sh

    - os: osx
      compiler: clang
      osx_image: xcode10.3
      script: ./code/build/travis/ios.sh

    - os: osx
      compiler: clang
      osx_image: xcode11.2
      script: ./code/build/travis/ios.sh

    - language: android
      jdk: openjdk8
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28
          - extra-google-m2repository
          - extra-android-m2repository
      install:
        - echo y | sdkmanager "ndk-bundle"
        - ./setup.sh
      before_script:
        - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
      script: ./code/build/travis/android.sh

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get -qq update &&
      sudo apt-get -y install freeglut3-dev libsndfile1-dev libopenal-dev libxrandr-dev &&
      sudo apt-get -y install libc6:i386 libstdc++6:i386 ;
    fi

install:
  - ./setup.sh
